export const SHOW_FORUM="SHOW_FORUM";
export const ADD_THREAD="ADD_THREAD";
export const ADD_COMMENT="ADD_COMMENT";
export const SHOW_COURSES="SHOW_COURSES";
export const SHOW_SPECIALIZATION="SHOW_SPECIALIZATION";
export const SHOW_DEGREES="SHOW_DEGREES";
export const GET_PROFILE_INFO="GET_PROFILE_INFO";

