export const SHOW_PROJECTS = "SHOW_PROJECTS";
export const SHOW_ALL_PROJECTS = "SHOW_ALL_PROJECTS";

export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_PROJECTS_ERROR = 'GET_PROJECTS_ERROR';
export const GET_PROJECTS_LOADING = 'GET_PROJECTS_LOADING';

export const GET_SINGLE_PROJECT = 'GET_SINGLE_PROJECT';
export const GET_SINGLE_PROJECT_ERROR = 'GET_SINGLE_PROJECT_ERROR';
export const GET_SINGLE_PROJECT_LOADING = 'GET_SINGLE_PROJECT_LOADING';

export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const UPDATE_PROJECT_ERROR = 'UPDATE_PROJECT_ERROR';
export const UPDATE_PROJECT_LOADING = 'UPDATE_PROJECT_LOADING';

export const APPLY_FOR_PROJECT = 'APPLY_FOR_PROJECT';
export const APPLY_FOR_PROJECT_LOADING = 'APPLY_FOR_PROJECT_LOADING';
export const APPLY_FOR_PROJECT_ERROR = 'APPLY_FOR_PROJECT_ERROR';

export const SUBMIT_PROJECT = 'APPLY_FOR_PROJECT';
export const SUBMIT_PROJECT_LOADING = 'SUBMIT_PROJECT_LOADING';
export const SUBMIT_PROJECT_ERROR = 'SUBMIT_PROJECT_ERROR';