export const ADD_TICKET="ADD_TICKET";
export const ADD_TICKET_LOADING="ADD_TICKET_LOADING";
export const ADD_TICKET_ERROR="ADD_TICKET_ERROR";

export const GET_TICKETS="GET_TICKETS";
export const GET_TICKETS_LOADING="GET_TICKETS_LOADING";
export const GET_TICKETS_ERROR="GET_TICKETS_ERROR";

export const ACTION_ON_TICKET="ACTION_ON_TICKET";
export const ACTION_ON_TICKET_LOADING="ACTION_ON_TICKET_LOADING";
export const ACTION_ON_TICKET_ERROR="ACTION_ON_TICKET_ERROR";
